//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtherealModManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EtherealModManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string BtnHelp {
            get {
                return ResourceManager.GetString("BtnHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Mods.
        /// </summary>
        public static string BtnMods {
            get {
                return ResourceManager.GetString("BtnMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string BtnPlay {
            get {
                return ResourceManager.GetString("BtnPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        public static string BtnPlaying {
            get {
                return ResourceManager.GetString("BtnPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string BtnSettings {
            get {
                return ResourceManager.GetString("BtnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop.
        /// </summary>
        public static string BtnWorkshop {
            get {
                return ResourceManager.GetString("BtnWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your distributed version of the game. \nYou can change your distribution in the settings..
        /// </summary>
        public static string DistributionContent {
            get {
                return ResourceManager.GetString("DistributionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Store.
        /// </summary>
        public static string DistributionNo {
            get {
                return ResourceManager.GetString("DistributionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution.
        /// </summary>
        public static string DistributionTitle {
            get {
                return ResourceManager.GetString("DistributionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam.
        /// </summary>
        public static string DistributionYes {
            get {
                return ResourceManager.GetString("DistributionYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game was not found. The program can attempt to automatically detect the game by running it for a few seconds..
        /// </summary>
        public static string GameNotFoundContent {
            get {
                return ResourceManager.GetString("GameNotFoundContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string GameNotFoundNo {
            get {
                return ResourceManager.GetString("GameNotFoundNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game not found.
        /// </summary>
        public static string GameNotFoundTitle {
            get {
                return ResourceManager.GetString("GameNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string GameNotFoundYes {
            get {
                return ResourceManager.GetString("GameNotFoundYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string LblChangelog {
            get {
                return ResourceManager.GetString("LblChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the game executable.
        /// </summary>
        public static string SelectGameExecutable {
            get {
                return ResourceManager.GetString("SelectGameExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a simple mod manager for Halo Wars: Definitive Edition. You can use this tool to install, update, and remove mods with ease. Enjoy!.
        /// </summary>
        public static string WelcomeContent {
            get {
                return ResourceManager.GetString("WelcomeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Ethereal Mod Manager!.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it!.
        /// </summary>
        public static string WelcomeYes {
            get {
                return ResourceManager.GetString("WelcomeYes", resourceCulture);
            }
        }
    }
}
