//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ethereal.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ethereal.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a mod.
        /// </summary>
        public static string AddModDialog {
            get {
                return ResourceManager.GetString("AddModDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string BtnHelp {
            get {
                return ResourceManager.GetString("BtnHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string BtnModPageAdd {
            get {
                return ResourceManager.GetString("BtnModPageAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play this mod.
        /// </summary>
        public static string BtnModPagePlayThis {
            get {
                return ResourceManager.GetString("BtnModPagePlayThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string BtnModPageRefresh {
            get {
                return ResourceManager.GetString("BtnModPageRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string BtnModPageRemove {
            get {
                return ResourceManager.GetString("BtnModPageRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Mods.
        /// </summary>
        public static string BtnMods {
            get {
                return ResourceManager.GetString("BtnMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string BtnPlay {
            get {
                return ResourceManager.GetString("BtnPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        public static string BtnPlaying {
            get {
                return ResourceManager.GetString("BtnPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string BtnSettings {
            get {
                return ResourceManager.GetString("BtnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop.
        /// </summary>
        public static string BtnWorkshop {
            get {
                return ResourceManager.GetString("BtnWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your distributed version of the game. {0}You can change your distribution in the settings..
        /// </summary>
        public static string DistributionContent {
            get {
                return ResourceManager.GetString("DistributionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS.
        /// </summary>
        public static string DistributionNo {
            get {
                return ResourceManager.GetString("DistributionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution.
        /// </summary>
        public static string DistributionTitle {
            get {
                return ResourceManager.GetString("DistributionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam.
        /// </summary>
        public static string DistributionYes {
            get {
                return ResourceManager.GetString("DistributionYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game was not found. The program can attempt to automatically detect the game by running it for a few seconds..
        /// </summary>
        public static string GameDetectionContent {
            get {
                return ResourceManager.GetString("GameDetectionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string GameDetectionNo {
            get {
                return ResourceManager.GetString("GameDetectionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game not found.
        /// </summary>
        public static string GameDetectionTitle {
            get {
                return ResourceManager.GetString("GameDetectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string GameDetectionYes {
            get {
                return ResourceManager.GetString("GameDetectionYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the game executable.
        /// </summary>
        public static string GameExecutableDialogTitle {
            get {
                return ResourceManager.GetString("GameExecutableDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        public static string LblChangelog {
            get {
                return ResourceManager.GetString("LblChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to set your mod directory? Head to the settings tab..
        /// </summary>
        public static string LblModPageHelp {
            get {
                return ResourceManager.GetString("LblModPageHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select a mod to remove!.
        /// </summary>
        public static string RemoveModContent {
            get {
                return ResourceManager.GetString("RemoveModContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Mod.
        /// </summary>
        public static string RemoveModTitle {
            get {
                return ResourceManager.GetString("RemoveModTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it!.
        /// </summary>
        public static string RemoveModYes {
            get {
                return ResourceManager.GetString("RemoveModYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucessfully imported {0}.
        /// </summary>
        public static string SelectModContent {
            get {
                return ResourceManager.GetString("SelectModContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Mod.
        /// </summary>
        public static string SelectModTitle {
            get {
                return ResourceManager.GetString("SelectModTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it!.
        /// </summary>
        public static string SelectModYes {
            get {
                return ResourceManager.GetString("SelectModYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a simple mod manager for Halo Wars: Definitive Edition. {0}You can use this tool to install, update, and remove mods with ease. Enjoy!.
        /// </summary>
        public static string WelcomeContent {
            get {
                return ResourceManager.GetString("WelcomeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Ethereal Mod Manager!.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it!.
        /// </summary>
        public static string WelcomeYes {
            get {
                return ResourceManager.GetString("WelcomeYes", resourceCulture);
            }
        }
    }
}
